// This file is generated by Slice Machine. Update with care!

import ImageGallery from './ImageGallery';
import TextBlock from './TextBlock';
import TextImage from './TextImage';

export {
	ImageGallery,
	TextBlock,
	TextImage,
};

export const components = {
	image_gallery: ImageGallery,
	text_block: TextBlock,
	text_image: TextImage,
};
